#! /bin/sh


NAME=Radio2_4r
DAEMON=/opt/Recever/$NAME
DIR_NAME=/etc/init.d/$NAME

echo "installation en deamon"

rm -r -f /opt/Recever
mkdir /opt/Recever

cp -r Lparam/ /opt/Recever/Lparam
cp  make /opt/Recever/make
chmod +x make
cp mainR.cpp /opt/Recever/mainR.cpp

cp LuncherDeamon $DIR_NAME

chown -R root $DIR_NAME
chgrp -R root $DIR_NAME
chmod -R 771 $DIR_NAME

#on compile le code source
cd /opt/Recever/
./make

# suppression line dynamique si ceux si existe

rm -f /etc/rc0.d/K01Radio2_4r
rm -f /etc/rc1.d/K01Radio2_4r
rm -f /etc/rc2.d/S01Radio2_4r
rm -f /etc/rc3.d/S01Radio2_4r
rm -f /etc/rc4.d/S01Radio2_4r
rm -f /etc/rc5.d/S01Radio2_4r
rm -f /etc/rc6.d/K01Radio2_4r

# creation des lien dynamique nessecaire au deamon

ln -s $DIR_NAME /etc/rc0.d/K01Radio2_4r
ln -s $DIR_NAME /etc/rc1.d/K01Radio2_4r
ln -s $DIR_NAME /etc/rc6.d/K01Radio2_4r
ln -s $DIR_NAME /etc/rc2.d/S01Radio2_4r
ln -s $DIR_NAME /etc/rc3.d/S01Radio2_4r
ln -s $DIR_NAME /etc/rc4.d/S01Radio2_4r
ln -s $DIR_NAME /etc/rc5.d/S01Radio2_4r

#redemarrage

sudo reboot 
