#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="recepteur radio 2.4Ghz"
NAME=Radio2_4r
DAEMON=/opt/Recever/$NAME
DAEMON_ARGS=""
SCRIPTNAME=/etc/init.d/$NAME

case $1 in
  start)
	$DAEMON &
	echo $DAEMON "start"
  ;;
  stop)
	killall -9 $NAME
  ;;
  restart|force-reload)
	killall -9 $NAME
	$DAEMON &

  ;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
